spring:
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bookdb
    driverClassName: org.h2.Driver

  data:
    mongodb:
      uri: mongodb://localhost
      port: 0 #27017
      database: SpringBatchExampleDB
logging:
  level:
    org.springframework.batch: debug